### PR TITLE
PHP 7.2 - revised

### PR DESCRIPTION
**Pull request by wiese**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Like this the `make ci` command will only run tests with PHP 7.1. Is that change intentional? (I think it's fine, just double checking you did not forgetti something)

**Comment by wiese** [comment]
@JeroenDeDauw That is definitely not intentional. But are you referring to the `README.md` "advance use" part? The phpunit target of make runs against both services.

**Comment by wiese** [comment]
If it would help at all we could _explicitly_ build the service containers all at once before invoking them so that the interesting test output is less scattered in the log. But this surely does have its downsides, too.

**Comment by JeroenDeDauw** [comment]
Oh the tests still run with both... such a blind Jeroen

**Pull request merged**
