### PR TITLE
Add SucceedingEmailValidator

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Having this would have been useful for stuff I am currently doing on the Donation BC

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
image

Dunno how to locally ignore something in phpstan. This is global:

https://github.com/phpstan/phpstan#ignore-error-messages-with-regular-expresions

**Comment by wiese** [comment]
Why not fix the underlying issue? https://github.com/wmde/FundraisingFrontend/pulls?utf8=%E2%9C%93&q=is%3Apr%20constructor%20stan

**Comment by JeroenDeDauw** [comment]
That requires a bunch of refactoring and is a breaking change for this package. Why do that effort? Personally I'm totally fine with this stub. Do you think it is problematic?

**Comment by JeroenDeDauw** [comment]
Woha, blast from the past :)

**Pull request merged**
